//
// Generated by JTB 1.3.2
//
package miniX10.visitor;

import miniX10.syntaxtree.*;
import java.util.*;

/**
 * A skeleton output formatter for your language grammar.  Using the
 * add() method along with force(), indent(), and outdent(), you can
 * easily specify how this visitor will format the given syntax tree.
 * See the JTB documentation for more details.
 *
 * Pass your syntax tree to this visitor, and then to the TreeDumper
 * visitor in order to "pretty print" your tree.
 */
public class TreeFormatter extends DepthFirstVisitor {
   private Vector<FormatCommand> cmdQueue = new Vector<FormatCommand>();
   private boolean lineWrap;
   private int wrapWidth;
   private int indentAmt;
   private int curLine = 1;
   private int curColumn = 1;
   private int curIndent = 0;

   /**
    * The default constructor assumes an indentation amount of 3 spaces
    * and no line-wrap.  You may alternately use the other constructor to
    * specify your own indentation amount and line width.
    */
   public TreeFormatter() { this(3, 0); }

   /**
    * This constructor accepts an indent amount and a line width which is
    * used to wrap long lines.  If a token's beginColumn value is greater
    * than the specified wrapWidth, it will be moved to the next line and
    * indented one extra level.  To turn off line-wrapping, specify a
    * wrapWidth of 0.
    *
    * @param   indentAmt   Amount of spaces per indentation level.
    * @param   wrapWidth   Wrap lines longer than wrapWidth.  0 for no wrap.
    */
   public TreeFormatter(int indentAmt, int wrapWidth) {
      this.indentAmt = indentAmt;
      this.wrapWidth = wrapWidth;

      if ( wrapWidth > 0 )
         lineWrap = true;
      else
         lineWrap = false;
   }

   /**
    * Accepts a NodeListInterface object and performs an optional format
    * command between each node in the list (but not after the last node).
    */
   protected void processList(NodeListInterface n) {
      processList(n, null);
   }

   protected void processList(NodeListInterface n, FormatCommand cmd) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         if ( cmd != null && e.hasMoreElements() )
            cmdQueue.addElement(cmd);
      }
   }

   /**
    * A Force command inserts a line break and indents the next line to
    * the current indentation level.  Use "add(force());".
    */
   protected FormatCommand force() { return force(1); }
   protected FormatCommand force(int i) {
      return new FormatCommand(FormatCommand.FORCE, i);
   }

   /**
    * An Indent command increases the indentation level by one (or a
    * user-specified amount).  Use "add(indent());".
    */
   protected FormatCommand indent() { return indent(1); }
   protected FormatCommand indent(int i) {
      return new FormatCommand(FormatCommand.INDENT, i);
   }

   /**
    * An Outdent command is the reverse of the Indent command: it reduces
    * the indentation level.  Use "add(outdent());".
    */
   protected FormatCommand outdent() { return outdent(1); }
   protected FormatCommand outdent(int i) {
      return new FormatCommand(FormatCommand.OUTDENT, i);
   }

   /**
    * A Space command simply adds one or a user-specified number of
    * spaces between tokens.  Use "add(space());".
    */
   protected FormatCommand space() { return space(1); }
   protected FormatCommand space(int i) {
      return new FormatCommand(FormatCommand.SPACE, i);
   }

   /**
    * Use this method to add FormatCommands to the command queue to be
    * executed when the next token in the tree is visited.
    */
   protected void add(FormatCommand cmd) {
      cmdQueue.addElement(cmd);
   }

   /**
    * Executes the commands waiting in the command queue, then inserts the
    * proper location information into the current NodeToken.
    *
    * If there are any special tokens preceding this token, they will be
    * given the current location information.  The token will follow on
    * the next line, at the proper indentation level.  If this is not the
    * behavior you want from special tokens, feel free to modify this
    * method.
    */
   public void visit(NodeToken n) {
      for ( Enumeration<FormatCommand> e = cmdQueue.elements(); e.hasMoreElements(); ) {
         FormatCommand cmd = e.nextElement();
         switch ( cmd.getCommand() ) {
         case FormatCommand.FORCE :
            curLine += cmd.getNumCommands();
            curColumn = curIndent + 1;
            break;
         case FormatCommand.INDENT :
            curIndent += indentAmt * cmd.getNumCommands();
            break;
         case FormatCommand.OUTDENT :
            if ( curIndent >= indentAmt )
               curIndent -= indentAmt * cmd.getNumCommands();
            break;
         case FormatCommand.SPACE :
            curColumn += cmd.getNumCommands();
            break;
         default :
            throw new TreeFormatterException(
               "Invalid value in command queue.");
         }
      }

      cmdQueue.removeAllElements();

      //
      // Handle all special tokens preceding this NodeToken
      //
      if ( n.numSpecials() > 0 )
         for ( Enumeration<NodeToken> e = n.specialTokens.elements();
               e.hasMoreElements(); ) {
            NodeToken special = e.nextElement();

            //
            // -Place the token.
            // -Move cursor to next line after the special token.
            // -Don't update curColumn--want to keep current indent level.
            //
            placeToken(special, curLine, curColumn);
            curLine = special.endLine + 1;
         }

      placeToken(n, curLine, curColumn);
      curLine = n.endLine;
      curColumn = n.endColumn;
   }

   /**
    * Inserts token location (beginLine, beginColumn, endLine, endColumn)
    * information into the NodeToken.  Takes into account line-wrap.
    * Does not update curLine and curColumn.
    */
   private void placeToken(NodeToken n, int line, int column) {
      int length = n.tokenImage.length();

      //
      // Find beginning of token.  Only line-wrap for single-line tokens
      //
      if ( !lineWrap || n.tokenImage.indexOf('\n') != -1 ||
           column + length <= wrapWidth )
         n.beginColumn = column;
      else {
         ++line;
         column = curIndent + indentAmt + 1;
         n.beginColumn = column;
      }

      n.beginLine = line;

      //
      // Find end of token; don't count \n if it's the last character
      //
      for ( int i = 0; i < length; ++i ) {
         if ( n.tokenImage.charAt(i) == '\n' && i < length - 1 ) {
            ++line;
            column = 1;
         }
         else
            ++column;
      }

      n.endLine = line;
      n.endColumn = column;
   }

   //
   // User-generated visitor methods below
   //

   /**
    * nodeListOptional -> ( TopLevelDeclaration() )*
    * nodeToken -> <EOF>
    */
   public void visit(File n) {
      if ( n.nodeListOptional.present() ) {
         processList(n.nodeListOptional);
      }
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> MainClass()
    *       | ClassDeclaration()
    */
   public void visit(TopLevelDeclaration n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "class"
    * identifier -> Identifier()
    * nodeToken2 -> "{"
    * nodeToken3 -> "public"
    * nodeToken4 -> "static"
    * nodeToken5 -> "void"
    * nodeToken6 -> "main"
    * nodeToken7 -> "("
    * nodeToken8 -> "String"
    * nodeToken9 -> "["
    * nodeToken10 -> "]"
    * identifier1 -> Identifier()
    * nodeToken11 -> ")"
    * nodeToken12 -> "{"
    * statement -> Statement()
    * nodeToken13 -> "}"
    * nodeToken14 -> "}"
    */
   public void visit(MainClass n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
      n.nodeToken8.accept(this);
      n.nodeToken9.accept(this);
      n.nodeToken10.accept(this);
      n.identifier1.accept(this);
      n.nodeToken11.accept(this);
      n.nodeToken12.accept(this);
      n.statement.accept(this);
      n.nodeToken13.accept(this);
      n.nodeToken14.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( ClassMember() )*
    * nodeToken2 -> "}"
    */
   public void visit(ClassDeclaration n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      if ( n.nodeListOptional.present() ) {
         processList(n.nodeListOptional);
      }
      n.nodeToken2.accept(this);
   }

   /**
    * nodeChoice -> MethodDeclaration()
    *       | ConstantDeclaration()
    *       | UpdatableFieldDeclaration()
    */
   public void visit(ClassMember n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "static"
    * nodeToken2 -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken3 -> "="
    * expression -> Expression()
    * nodeToken4 -> ";"
    */
   public void visit(ConstantDeclaration n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken3.accept(this);
      n.expression.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "public"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> ";"
    */
   public void visit(UpdatableFieldDeclaration n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "public"
    * returnType -> ReturnType()
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(MethodDeclaration n) {
      n.nodeToken.accept(this);
      n.returnType.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
      n.nodeToken2.accept(this);
      n.block.accept(this);
   }

   /**
    * formalParameter -> FormalParameter()
    * nodeListOptional -> ( FormalParameterRest() )*
    */
   public void visit(FormalParameterList n) {
      n.formalParameter.accept(this);
      if ( n.nodeListOptional.present() ) {
         processList(n.nodeListOptional);
      }
   }

   /**
    * nodeChoice -> FinalFormalParameter()
    *       | UpdatableFormalParameter()
    */
   public void visit(FormalParameter n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "final"
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(FinalFormalParameter n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(UpdatableFormalParameter n) {
      n.type.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> ","
    * formalParameter -> FormalParameter()
    */
   public void visit(FormalParameterRest n) {
      n.nodeToken.accept(this);
      n.formalParameter.accept(this);
   }

   /**
    * nodeChoice -> VoidType()
    *       | Type()
    */
   public void visit(ReturnType n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "void"
    */
   public void visit(VoidType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> UpdatableArrayType()
    *       | NonArrayType()
    */
   public void visit(Type n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nonArrayType -> NonArrayType()
    * nodeToken -> "["
    * nodeToken1 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken2 -> "]"
    */
   public void visit(UpdatableArrayType n) {
      n.nonArrayType.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "rank"
    * nodeToken1 -> "=="
    * integerLiteral -> IntegerLiteral()
    */
   public void visit(RankEquation n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.integerLiteral.accept(this);
   }

   /**
    * nodeChoice -> BooleanType()
    *       | IntegerType()
    *       | DoubleType()
    *       | StringType()
    *       | PlaceType()
    *       | DistType()
    *       | RegionType()
    *       | PointType()
    *       | ClassNameType()
    */
   public void visit(NonArrayType n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "boolean"
    */
   public void visit(BooleanType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "int"
    */
   public void visit(IntegerType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "double"
    */
   public void visit(DoubleType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "String"
    */
   public void visit(StringType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "place"
    */
   public void visit(PlaceType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "dist"
    * nodeToken1 -> "("
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> ")"
    */
   public void visit(DistType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "region"
    * nodeToken1 -> "("
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> ")"
    */
   public void visit(RegionType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "point"
    * nodeToken1 -> "("
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> ")"
    */
   public void visit(PointType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    */
   public void visit(ClassNameType n) {
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> Assignment()
    *       | AsyncStatement()
    *       | Block()
    *       | FinishStatement()
    *       | IfStatement()
    *       | LoopStatement()
    *       | PostfixStatement()
    *       | PrintlnStatement()
    *       | ReturnStatement()
    *       | ThrowStatement()
    *       | WhileStatement()
    */
   public void visit(Statement n) {
      n.nodeChoice.accept(this);
   }

   /**
    * expression -> Expression()
    * nodeToken -> "="
    * expression1 -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(Assignment n) {
      n.expression.accept(this);
      n.nodeToken.accept(this);
      n.expression1.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "async"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(AsyncStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeToken -> "{"
    * nodeListOptional -> ( BlockStatement() )*
    * nodeToken1 -> "}"
    */
   public void visit(Block n) {
      n.nodeToken.accept(this);
      if ( n.nodeListOptional.present() ) {
         processList(n.nodeListOptional);
      }
      n.nodeToken1.accept(this);
   }

   /**
    * nodeChoice -> FinalVariableDeclaration()
    *       | UpdatableVariableDeclaration()
    *       | Statement()
    */
   public void visit(BlockStatement n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> "="
    * expression -> Expression()
    * nodeToken2 -> ";"
    */
   public void visit(FinalVariableDeclaration n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(UpdatableVariableDeclaration n) {
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "finish"
    * statement -> Statement()
    */
   public void visit(FinishStatement n) {
      n.nodeToken.accept(this);
      n.statement.accept(this);
   }

   /**
    * nodeToken -> "if"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * statement -> Statement()
    * nodeOptional -> [ ElseClause() ]
    */
   public void visit(IfStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
      n.statement.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
   }

   /**
    * nodeToken -> "else"
    * statement -> Statement()
    */
   public void visit(ElseClause n) {
      n.nodeToken.accept(this);
      n.statement.accept(this);
   }

   /**
    * nodeToken -> "for"
    * nodeToken1 -> "("
    * pointType -> PointType()
    * explodedSpecification -> ExplodedSpecification()
    * nodeToken2 -> ":"
    * expression -> Expression()
    * nodeToken3 -> ")"
    * statement -> Statement()
    */
   public void visit(LoopStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.pointType.accept(this);
      n.explodedSpecification.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
      n.nodeToken3.accept(this);
      n.statement.accept(this);
   }

   /**
    * identifierList -> IdentifierList()
    */
   public void visit(ExplodedSpecification n) {
      n.identifierList.accept(this);
   }

   /**
    * identifier -> Identifier()
    */
   public void visit(PointName n) {
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> "["
    * identifier -> Identifier()
    * nodeListOptional -> ( IdentifierRest() )*
    * nodeToken1 -> "]"
    */
   public void visit(IdentifierList n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      if ( n.nodeListOptional.present() ) {
         processList(n.nodeListOptional);
      }
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> ","
    * identifier -> Identifier()
    */
   public void visit(IdentifierRest n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
   }

   /**
    * expression -> Expression()
    * nodeToken -> ";"
    */
   public void visit(PostfixStatement n) {
      n.expression.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "System.out.println"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintlnStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "return"
    * nodeOptional -> [ Expression() ]
    * nodeToken1 -> ";"
    */
   public void visit(ReturnStatement n) {
      n.nodeToken.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "throw"
    * nodeToken1 -> "new"
    * nodeToken2 -> "RuntimeException"
    * nodeToken3 -> "("
    * expression -> Expression()
    * nodeToken4 -> ")"
    * nodeToken5 -> ";"
    */
   public void visit(ThrowStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.expression.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "while"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * statement -> Statement()
    */
   public void visit(WhileStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
      n.statement.accept(this);
   }

   /**
    * nodeChoice -> InclusiveOrExpression()
    *       | EqualsExpression()
    *       | NotEqualsExpression()
    *       | GreaterThanExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivideExpression()
    *       | SinExpression()
    *       | CosExpression()
    *       | PowExpression()
    *       | AbsExpression()
    *       | MapExpression()
    *       | RegionConstant()
    *       | UnaryMinusExpression()
    *       | CoercionToIntExpression()
    *       | CoercionToDoubleExpression()
    *       | TypeAnnotatedExpression()
    *       | FactoryBlock()
    *       | ArrayAccess()
    *       | DotDistribution()
    *       | DotIsFirst()
    *       | DotMethodCall()
    *       | DotIdentifier()
    *       | PrimaryExpression()
    */
   public void visit(Expression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "|"
    * expression -> Expression()
    */
   public void visit(InclusiveOrExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "=="
    * expression -> Expression()
    */
   public void visit(EqualsExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "!="
    * expression -> Expression()
    */
   public void visit(NotEqualsExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> ">"
    * expression -> Expression()
    */
   public void visit(GreaterThanExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "+"
    * expression -> Expression()
    */
   public void visit(PlusExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "-"
    * expression -> Expression()
    */
   public void visit(MinusExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "*"
    * expression -> Expression()
    */
   public void visit(TimesExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "/"
    * expression -> Expression()
    */
   public void visit(DivideExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "sin"
    * nodeToken3 -> "("
    * expression -> Expression()
    * nodeToken4 -> ")"
    */
   public void visit(SinExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.expression.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "cos"
    * nodeToken3 -> "("
    * expression -> Expression()
    * nodeToken4 -> ")"
    */
   public void visit(CosExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.expression.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "pow"
    * nodeToken3 -> "("
    * expression -> Expression()
    * nodeToken4 -> ","
    * expression1 -> Expression()
    * nodeToken5 -> ")"
    */
   public void visit(PowExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.expression.accept(this);
      n.nodeToken4.accept(this);
      n.expression1.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "abs"
    * nodeToken3 -> "("
    * expression -> Expression()
    * nodeToken4 -> ")"
    */
   public void visit(AbsExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.expression.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "->"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(MapExpression n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.primaryExpression1.accept(this);
   }

   /**
    * nodeToken -> "["
    * colonExpression -> ColonExpression()
    * nodeOptional -> ( ColonRest() )?
    * nodeToken1 -> "]"
    */
   public void visit(RegionConstant n) {
      n.nodeToken.accept(this);
      n.colonExpression.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> ","
    * colonExpression -> ColonExpression()
    */
   public void visit(ColonRest n) {
      n.nodeToken.accept(this);
      n.colonExpression.accept(this);
   }

   /**
    * nodeChoice -> ColonPair()
    *       | Expression()
    */
   public void visit(ColonExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * expression -> Expression()
    * nodeToken -> ":"
    * expression1 -> Expression()
    */
   public void visit(ColonPair n) {
      n.expression.accept(this);
      n.nodeToken.accept(this);
      n.expression1.accept(this);
   }

   /**
    * nodeToken -> "-"
    * primaryExpression -> PrimaryExpression()
    */
   public void visit(UnaryMinusExpression n) {
      n.nodeToken.accept(this);
      n.primaryExpression.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "int"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToIntExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "double"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToDoubleExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * typeAnnotation -> TypeAnnotation()
    * nodeToken1 -> ")"
    * expression -> Expression()
    */
   public void visit(TypeAnnotatedExpression n) {
      n.nodeToken.accept(this);
      n.typeAnnotation.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeChoice -> UpdatableArrayType()
    *       | DistType()
    */
   public void visit(TypeAnnotation n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeChoice -> Literal()
    *       | This()
    *       | AllocationExpression()
    *       | Identifier()
    */
   public void visit(PrimaryExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "this"
    */
   public void visit(This n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "dist.factory.block"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    */
   public void visit(FactoryBlock n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "["
    * expressionList -> ExpressionList()
    * nodeToken1 -> "]"
    */
   public void visit(ArrayAccess n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.expressionList.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( ExpressionList() )?
    * nodeToken2 -> ")"
    */
   public void visit(DotMethodCall n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
      n.nodeToken2.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * nodeToken1 -> "distribution"
    */
   public void visit(DotDistribution n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * nodeToken1 -> "isFirst"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotIsFirst n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * identifier -> Identifier()
    */
   public void visit(DotIdentifier n) {
      n.primaryExpression.accept(this);
      n.nodeToken.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeChoice -> NewObject()
    *       | NewUpdatableArray()
    */
   public void visit(AllocationExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "new"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> [ ExpressionList() ]
    * nodeToken2 -> ")"
    */
   public void visit(NewObject n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "new"
    * nonArrayType -> NonArrayType()
    * nodeToken1 -> "["
    * identifier -> Identifier()
    * nodeToken2 -> "]"
    * nodeOptional -> [ ArrayInitializer() ]
    */
   public void visit(NewUpdatableArray n) {
      n.nodeToken.accept(this);
      n.nonArrayType.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      if ( n.nodeOptional.present() ) {
         n.nodeOptional.accept(this);
      }
   }

   /**
    * nodeChoice -> IntegerLiteral()
    *       | FloatingPointLiteral()
    *       | StringLiteral()
    *       | HereLiteral()
    *       | DistUnique()
    */
   public void visit(Literal n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <FLOATING_POINT_LITERAL>
    */
   public void visit(FloatingPointLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <STRING_LITERAL>
    */
   public void visit(StringLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "here"
    */
   public void visit(HereLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "dist.UNIQUE"
    */
   public void visit(DistUnique n) {
      n.nodeToken.accept(this);
   }

   /**
    * expression -> Expression()
    * nodeListOptional -> ( ArgumentRest() )*
    */
   public void visit(ExpressionList n) {
      n.expression.accept(this);
      if ( n.nodeListOptional.present() ) {
         processList(n.nodeListOptional);
      }
   }

   /**
    * nodeToken -> ","
    * expression -> Expression()
    */
   public void visit(ArgumentRest n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * pointType -> PointType()
    * explodedSpecification -> ExplodedSpecification()
    * nodeToken1 -> ")"
    * block -> Block()
    */
   public void visit(ArrayInitializer n) {
      n.nodeToken.accept(this);
      n.pointType.accept(this);
      n.explodedSpecification.accept(this);
      n.nodeToken1.accept(this);
      n.block.accept(this);
   }

}

class FormatCommand {
   public static final int FORCE = 0;
   public static final int INDENT = 1;
   public static final int OUTDENT = 2;
   public static final int SPACE = 3;

   private int command;
   private int numCommands;

   FormatCommand(int command, int numCommands) {
      this.command = command;
      this.numCommands = numCommands;
   }

   public int getCommand()             { return command; }
   public int getNumCommands()         { return numCommands; }
   public void setCommand(int i)       { command = i; }
   public void setNumCommands(int i)   { numCommands = i; }
}

class TreeFormatterException extends RuntimeException {
   TreeFormatterException()         { super(); }
   TreeFormatterException(String s) { super(s); }
}
