//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "["
 * expressionList -> ExpressionList()
 * nodeToken1 -> "]"
 */
public class ArrayAccess implements Node {
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public ExpressionList expressionList;
   public NodeToken nodeToken1;

   public ArrayAccess(PrimaryExpression n0, NodeToken n1, ExpressionList n2, NodeToken n3) {
      primaryExpression = n0;
      nodeToken = n1;
      expressionList = n2;
      nodeToken1 = n3;
   }

   public ArrayAccess(PrimaryExpression n0, ExpressionList n1) {
      primaryExpression = n0;
      nodeToken = new NodeToken("[");
      expressionList = n1;
      nodeToken1 = new NodeToken("]");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

