//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * expression -> Expression()
 * nodeToken -> "="
 * expression1 -> Expression()
 * nodeToken1 -> ";"
 */
public class Assignment implements Node {
   public Expression expression;
   public NodeToken nodeToken;
   public Expression expression1;
   public NodeToken nodeToken1;

   public Assignment(Expression n0, NodeToken n1, Expression n2, NodeToken n3) {
      expression = n0;
      nodeToken = n1;
      expression1 = n2;
      nodeToken1 = n3;
   }

   public Assignment(Expression n0, Expression n1) {
      expression = n0;
      nodeToken = new NodeToken("=");
      expression1 = n1;
      nodeToken1 = new NodeToken(";");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

