//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "async"
 * nodeToken1 -> "("
 * expression -> Expression()
 * nodeToken2 -> ")"
 * block -> Block()
 */
public class AsyncStatement implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public Expression expression;
   public NodeToken nodeToken2;
   public Block block;

   public AsyncStatement(NodeToken n0, NodeToken n1, Expression n2, NodeToken n3, Block n4) {
      nodeToken = n0;
      nodeToken1 = n1;
      expression = n2;
      nodeToken2 = n3;
      block = n4;
   }

   public AsyncStatement(Expression n0, Block n1) {
      nodeToken = new NodeToken("async");
      nodeToken1 = new NodeToken("(");
      expression = n0;
      nodeToken2 = new NodeToken(")");
      block = n1;
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

