//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * primaryExpression -> PrimaryExpression()
 * nodeToken -> "."
 * nodeToken1 -> "distribution"
 */
public class DotDistribution implements Node {
   public PrimaryExpression primaryExpression;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;

   public DotDistribution(PrimaryExpression n0, NodeToken n1, NodeToken n2) {
      primaryExpression = n0;
      nodeToken = n1;
      nodeToken1 = n2;
   }

   public DotDistribution(PrimaryExpression n0) {
      primaryExpression = n0;
      nodeToken = new NodeToken(".");
      nodeToken1 = new NodeToken("distribution");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

