//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "final"
 * type -> Type()
 * identifier -> Identifier()
 */
public class FinalFormalParameter implements Node {
   public NodeToken nodeToken;
   public Type type;
   public Identifier identifier;

   public FinalFormalParameter(NodeToken n0, Type n1, Identifier n2) {
      nodeToken = n0;
      type = n1;
      identifier = n2;
   }

   public FinalFormalParameter(Type n0, Identifier n1) {
      nodeToken = new NodeToken("final");
      type = n0;
      identifier = n1;
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

