//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "["
 * identifier -> Identifier()
 * nodeListOptional -> ( IdentifierRest() )*
 * nodeToken1 -> "]"
 */
public class IdentifierList implements Node {
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeListOptional nodeListOptional;
   public NodeToken nodeToken1;

   public IdentifierList(NodeToken n0, Identifier n1, NodeListOptional n2, NodeToken n3) {
      nodeToken = n0;
      identifier = n1;
      nodeListOptional = n2;
      nodeToken1 = n3;
   }

   public IdentifierList(Identifier n0, NodeListOptional n1) {
      nodeToken = new NodeToken("[");
      identifier = n0;
      nodeListOptional = n1;
      nodeToken1 = new NodeToken("]");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

