//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "for"
 * nodeToken1 -> "("
 * pointType -> PointType()
 * explodedSpecification -> ExplodedSpecification()
 * nodeToken2 -> ":"
 * expression -> Expression()
 * nodeToken3 -> ")"
 * statement -> Statement()
 */
public class LoopStatement implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public PointType pointType;
   public ExplodedSpecification explodedSpecification;
   public NodeToken nodeToken2;
   public Expression expression;
   public NodeToken nodeToken3;
   public Statement statement;

   public LoopStatement(NodeToken n0, NodeToken n1, PointType n2, ExplodedSpecification n3, NodeToken n4, Expression n5, NodeToken n6, Statement n7) {
      nodeToken = n0;
      nodeToken1 = n1;
      pointType = n2;
      explodedSpecification = n3;
      nodeToken2 = n4;
      expression = n5;
      nodeToken3 = n6;
      statement = n7;
   }

   public LoopStatement(PointType n0, ExplodedSpecification n1, Expression n2, Statement n3) {
      nodeToken = new NodeToken("for");
      nodeToken1 = new NodeToken("(");
      pointType = n0;
      explodedSpecification = n1;
      nodeToken2 = new NodeToken(":");
      expression = n2;
      nodeToken3 = new NodeToken(")");
      statement = n3;
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

