//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "new"
 * identifier -> Identifier()
 * nodeToken1 -> "("
 * nodeOptional -> [ ExpressionList() ]
 * nodeToken2 -> ")"
 */
public class NewObject implements Node {
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeToken nodeToken1;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken2;

   public NewObject(NodeToken n0, Identifier n1, NodeToken n2, NodeOptional n3, NodeToken n4) {
      nodeToken = n0;
      identifier = n1;
      nodeToken1 = n2;
      nodeOptional = n3;
      nodeToken2 = n4;
   }

   public NewObject(Identifier n0, NodeOptional n1) {
      nodeToken = new NodeToken("new");
      identifier = n0;
      nodeToken1 = new NodeToken("(");
      nodeOptional = n1;
      nodeToken2 = new NodeToken(")");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

