//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeChoice -> BooleanType()
 *       | IntegerType()
 *       | DoubleType()
 *       | StringType()
 *       | PlaceType()
 *       | DistType()
 *       | RegionType()
 *       | PointType()
 *       | ClassNameType()
 */
public class NonArrayType implements Node {
   public NodeChoice nodeChoice;

   public NonArrayType(NodeChoice n0) {
      nodeChoice = n0;
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

