//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "["
 * colonExpression -> ColonExpression()
 * nodeOptional -> ( ColonRest() )?
 * nodeToken1 -> "]"
 */
public class RegionConstant implements Node {
   public NodeToken nodeToken;
   public ColonExpression colonExpression;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken1;

   public RegionConstant(NodeToken n0, ColonExpression n1, NodeOptional n2, NodeToken n3) {
      nodeToken = n0;
      colonExpression = n1;
      nodeOptional = n2;
      nodeToken1 = n3;
   }

   public RegionConstant(ColonExpression n0, NodeOptional n1) {
      nodeToken = new NodeToken("[");
      colonExpression = n0;
      nodeOptional = n1;
      nodeToken1 = new NodeToken("]");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

