//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "throw"
 * nodeToken1 -> "new"
 * nodeToken2 -> "RuntimeException"
 * nodeToken3 -> "("
 * expression -> Expression()
 * nodeToken4 -> ")"
 * nodeToken5 -> ";"
 */
public class ThrowStatement implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;
   public NodeToken nodeToken3;
   public Expression expression;
   public NodeToken nodeToken4;
   public NodeToken nodeToken5;

   public ThrowStatement(NodeToken n0, NodeToken n1, NodeToken n2, NodeToken n3, Expression n4, NodeToken n5, NodeToken n6) {
      nodeToken = n0;
      nodeToken1 = n1;
      nodeToken2 = n2;
      nodeToken3 = n3;
      expression = n4;
      nodeToken4 = n5;
      nodeToken5 = n6;
   }

   public ThrowStatement(Expression n0) {
      nodeToken = new NodeToken("throw");
      nodeToken1 = new NodeToken("new");
      nodeToken2 = new NodeToken("RuntimeException");
      nodeToken3 = new NodeToken("(");
      expression = n0;
      nodeToken4 = new NodeToken(")");
      nodeToken5 = new NodeToken(";");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

