//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "("
 * typeAnnotation -> TypeAnnotation()
 * nodeToken1 -> ")"
 * expression -> Expression()
 */
public class TypeAnnotatedExpression implements Node {
   public NodeToken nodeToken;
   public TypeAnnotation typeAnnotation;
   public NodeToken nodeToken1;
   public Expression expression;

   public TypeAnnotatedExpression(NodeToken n0, TypeAnnotation n1, NodeToken n2, Expression n3) {
      nodeToken = n0;
      typeAnnotation = n1;
      nodeToken1 = n2;
      expression = n3;
   }

   public TypeAnnotatedExpression(TypeAnnotation n0, Expression n1) {
      nodeToken = new NodeToken("(");
      typeAnnotation = n0;
      nodeToken1 = new NodeToken(")");
      expression = n1;
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

