//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "public"
 * type -> Type()
 * identifier -> Identifier()
 * nodeToken1 -> ";"
 */
public class UpdatableFieldDeclaration implements Node {
   public NodeToken nodeToken;
   public Type type;
   public Identifier identifier;
   public NodeToken nodeToken1;

   public UpdatableFieldDeclaration(NodeToken n0, Type n1, Identifier n2, NodeToken n3) {
      nodeToken = n0;
      type = n1;
      identifier = n2;
      nodeToken1 = n3;
   }

   public UpdatableFieldDeclaration(Type n0, Identifier n1) {
      nodeToken = new NodeToken("public");
      type = n0;
      identifier = n1;
      nodeToken1 = new NodeToken(";");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

