//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * type -> Type()
 * identifier -> Identifier()
 * nodeToken -> "="
 * expression -> Expression()
 * nodeToken1 -> ";"
 */
public class UpdatableVariableDeclaration implements Node {
   public Type type;
   public Identifier identifier;
   public NodeToken nodeToken;
   public Expression expression;
   public NodeToken nodeToken1;

   public UpdatableVariableDeclaration(Type n0, Identifier n1, NodeToken n2, Expression n3, NodeToken n4) {
      type = n0;
      identifier = n1;
      nodeToken = n2;
      expression = n3;
      nodeToken1 = n4;
   }

   public UpdatableVariableDeclaration(Type n0, Identifier n1, Expression n2) {
      type = n0;
      identifier = n1;
      nodeToken = new NodeToken("=");
      expression = n2;
      nodeToken1 = new NodeToken(";");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

