//
// Generated by JTB 1.3.2
//

package miniX10.syntaxtree;

/**
 * Grammar production:
 * nonArrayType -> NonArrayType()
 * nodeToken -> "["
 * nodeToken1 -> ":"
 * rankEquation -> RankEquation()
 * nodeToken2 -> "]"
 */
public class UpdatableArrayType implements Node {
   public NonArrayType nonArrayType;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public RankEquation rankEquation;
   public NodeToken nodeToken2;

   public UpdatableArrayType(NonArrayType n0, NodeToken n1, NodeToken n2, RankEquation n3, NodeToken n4) {
      nonArrayType = n0;
      nodeToken = n1;
      nodeToken1 = n2;
      rankEquation = n3;
      nodeToken2 = n4;
   }

   public UpdatableArrayType(NonArrayType n0, RankEquation n1) {
      nonArrayType = n0;
      nodeToken = new NodeToken("[");
      nodeToken1 = new NodeToken(":");
      rankEquation = n1;
      nodeToken2 = new NodeToken("]");
   }

   public void accept(miniX10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(miniX10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(miniX10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(miniX10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

